#!/usr/bin/env python3
"""
Darby Foundry Push Script (v0.3-compatible)
This script works with complex spec.yaml format using:
- repository.name
- structure.components[*].files
- readme.title/tagline/sections
"""

import os
import requests
import base64
import yaml
import shutil

# === Load secrets from GitHub Actions ===
GITHUB_TOKEN = os.environ['FOUNDRY_TOKEN_PERSONAL']
USERNAME = os.environ['FOUNDRY_USERNAME']

if USERNAME != "darbybailey":
    raise Exception("❌ Unauthorized user. Only darbybailey can run this workflow.")

# === Load the architecture spec ===
with open("spec.yaml", "r") as f:
    config = yaml.safe_load(f)

repo_info = config["repository"]
project_name = repo_info["name"]
components = config.get("structure", {}).get("components", [])
readme = config.get("readme", {})

# Flatten files and folders
files = []
folders = set()
for component in components:
    for file_path in component.get("files", []):
        files.append(file_path)
        folder_path = os.path.dirname(file_path)
        while folder_path and folder_path not in folders:
            folders.add(folder_path)
            folder_path = os.path.dirname(folder_path)
folders = sorted(folders)

# === Create the new repo via GitHub API ===
headers = {
    "Authorization": f"token {GITHUB_TOKEN}",
    "Accept": "application/vnd.github.v3+json"
}
repo_data = {
    "name": project_name,
    "private": repo_info.get("visibility", "public") != "public",
    "auto_init": True
}
res = requests.post("https://api.github.com/user/repos", headers=headers, json=repo_data)
if res.status_code != 201:
    raise Exception(f"❌ Repo creation failed: {res.text}")
print(f"✅ Repo created: https://github.com/{USERNAME}/{project_name}")

# === Clean up any old run ===
if os.path.exists(project_name):
    shutil.rmtree(project_name)

# === Create folders and files locally ===
os.makedirs(project_name, exist_ok=True)
os.chdir(project_name)

def create_nested(folder):
    parts = folder.strip("/").split("/")
    path = ""
    for part in parts:
        path = os.path.join(path, part)
        os.makedirs(path, exist_ok=True)

for folder in folders:
    create_nested(folder)

for file in files:
    with open(file, "w") as f:
        f.write("# Auto-generated by Foundry\n")

# === Generate README.md from spec.yaml ===
if readme:
    readme_lines = []
    if "title" in readme:
        readme_lines.append(f"# {readme['title']}\n")
    if "tagline" in readme:
        readme_lines.append(f"**{readme['tagline']}**\n")
    if "sections" in readme:
        for section in readme["sections"]:
            name = section.get("name", "").strip()
            content = section.get("content", "").strip()
            readme_lines.append(f"\n## {name}\n{content}\n")
    with open("README.md", "w") as f:
        f.write("\n".join(readme_lines))
    print("✅ README.md generated from spec.yaml")

# === Push files to new repo (create or update) ===
def push_file(path, content, repo):
    url = f"https://api.github.com/repos/{USERNAME}/{repo}/contents/{path}"
    encoded = base64.b64encode(content.encode()).decode()

    # Check if file already exists to get its sha
    r = requests.get(url, headers=headers)
    sha = r.json().get("sha") if r.status_code == 200 else None

    data = {
        "message": f"Add or update {path}",
        "content": encoded,
    }
    if sha:
        data["sha"] = sha

    r = requests.put(url, headers=headers, json=data)
    if r.status_code not in [201, 200]:
        print(f"⚠️ Failed to push {path}: {r.text}")
    else:
        print(f"✅ Pushed {path}")

for root, dirs, files in os.walk("."):
    for file in files:
        filepath = os.path.join(root, file)
        if ".git" in filepath:
            continue
        with open(filepath, "r") as f:
            content = f.read()
        repo_path = filepath.replace("./", "")
        push_file(repo_path, content, project_name)

# === Final cleanup ===
os.chdir("..")
shutil.rmtree(project_name)
print(f"🧹 Cleaned up local project folder: {project_name}")