#!/usr/bin/env python3
"""
Darby Foundry Push Script (v0.3-compatible)
- Handles 'repository', 'structure', and 'readme' from spec.yaml
- Always updates existing files using their SHA
"""

import os
import requests
import base64
import yaml
import shutil

# === Load secrets from GitHub Actions ===
GITHUB_TOKEN = os.environ['FOUNDRY_TOKEN_PERSONAL']
USERNAME = os.environ['FOUNDRY_USERNAME']

if USERNAME != "darbybailey":
    raise Exception("❌ Unauthorized user. Only darbybailey can run this workflow.")

# === Load the architecture spec ===
with open("spec.yaml", "r") as f:
    config = yaml.safe_load(f)

repo_info = config["repository"]
project_name = repo_info["name"]
components = config.get("structure", {}).get("components", [])
readme = config.get("readme", {})

# Flatten files and folders
files = []
folders = set()
for component in components:
    for file_path in component.get("files", []):
        files.append(file_path)
        folder_path = os.path.dirname(file_path)
        while folder_path and folder_path not in folders:
            folders.add(folder_path)
            folder_path = os.path.dirname(folder_path)
folders = sorted(folders)

# === GitHub API Setup ===
headers = {
    "Authorization": f"token {GITHUB_TOKEN}",
    "Accept": "application/vnd.github.v3+json"
}

# === Create repo (if it doesn't exist) ===
res = requests.get(f"https://api.github.com/repos/{USERNAME}/{project_name}", headers=headers)
if res.status_code == 404:
    repo_data = {
        "name": project_name,
        "private": repo_info.get("visibility", "public") != "public",
        "auto_init": True
    }
    res = requests.post("https://api.github.com/user/repos", headers=headers, json=repo_data)
    if res.status_code != 201:
        raise Exception(f"❌ Repo creation failed: {res.text}")
    print(f"✅ Repo created: https://github.com/{USERNAME}/{project_name}")
else:
    print(f"ℹ️ Repo already exists: https://github.com/{USERNAME}/{project_name}")

# === Clean up local build folder ===
if os.path.exists(project_name):
    shutil.rmtree(project_name)

os.makedirs(project_name, exist_ok=True)
os.chdir(project_name)

# === Create folder structure and empty files ===
def create_nested(folder):
    parts = folder.strip("/").split("/")
    path = ""
    for part in parts:
        path = os.path.join(path, part)
        os.makedirs(path, exist_ok=True)

for folder in folders:
    create_nested(folder)

for file in files:
    with open(file, "w") as f:
        f.write("# Auto-generated by Foundry\n")

# === Generate README.md ===
readme_path = "README.md"
if readme:
    lines = []
    if "title" in readme:
        lines.append(f"# {readme['title']}\n")
    if "tagline" in readme:
        lines.append(f"**{readme['tagline']}**\n")
    for section in readme.get("sections", []):
        lines.append(f"\n## {section.get('name')}\n{section.get('content')}\n")
    with open(readme_path, "w") as f:
        f.write("\n".join(lines))
    print("✅ README.md generated")

# === Push file (create or update with SHA) ===
def push_file(path, content, repo):
    url = f"https://api.github.com/repos/{USERNAME}/{repo}/contents/{path}"
    encoded = base64.b64encode(content.encode()).decode()

    # Try to get current SHA
    r = requests.get(url, headers=headers)
    sha = r.json().get("sha") if r.status_code == 200 else None

    data = {
        "message": f"Auto push: {path}",
        "content": encoded
    }
    if sha:
        data["sha"] = sha

    r = requests.put(url, headers=headers, json=data)
    if r.status_code not in [200, 201]:
        print(f"⚠️ Failed to push {path}: {r.status_code} {r.text}")
    else:
        print(f"✅ Pushed: {path}")

# === Walk and push all files ===
for root, _, filenames in os.walk("."):
    for filename in filenames:
        full_path = os.path.join(root, filename)
        if ".git" in full_path:
            continue
        with open(full_path, "r") as f:
            content = f.read()
        remote_path = full_path.replace("./", "")
        push_file(remote_path, content, project_name)

# === Cleanup ===
os.chdir("..")
shutil.rmtree(project_name)
print(f"🧹 Local project folder cleaned: {project_name}")